apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scihive-backend
bases:
    - ../base
resources:
  - postgres.yaml

patchesStrategicMerge:
    - web-server.yaml
        
secretGenerator:
  - name: web-env
    envs:
      - .env
    type: Opaque
