apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scihive-backend
bases:
    - ../base
resources:
  - postgres.yaml

patchesStrategicMerge:
    - web-server.yaml

secretGenerator:
  - name: web-server-secrets
    envs:
      - .secrets
    type: Opaque

configMapGenerator:
  - name: web-server-config
    literals:
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - FLASK_APP=src.app
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - EXTERNAL_BASE_URL=http://localhost:5000
