apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
  namespace: scihive-backend
spec:
  storageClassName: manual
  volumeName: redis-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi