version: "3.5"
services:
  web:
    build: .
    depends_on:
      - postgres
      - grobid
    volumes:
      - ./src:/usr/app/src
    ports:
      - "${PORT}:${PORT}"
    networks:
      - default
    env_file: .env
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  grobid:
    image: lfoppiano/grobid:0.6.1

