apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: web-server-image
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - src/**/*
  local:
    push: false
deploy:
  kubeContext: minikube
  kustomize:
    paths:
      - ./k8s
  kubectl:
    manifests:
      - ./k8s/scihive-backend.yaml
      - ./k8s/postgres.yaml
      - ./k8s/web-server.yaml
      - ./k8s/grobid.yaml
portForward:
  - resourceType: Service
    resourceName: web-server
    namespace: scihive-backend
    port: 5000
    localPort: 5000
  - resourceType: Service
    resourceName: grobid
    namespace: scihive-backend
    port: 8080
    localPort: 8080
