apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: web-server-image
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - src/**/*
  local:
    push: false
deploy:
  kubeContext: minikube
  kustomize:
    paths:
      - ./k8s

portForward:
  - resourceType: Service
    resourceName: postgres
    namespace: scihive-backend
    port: 5433
    localPort: 5432
