apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: main-ingress-ip
spec:
  backend:
    serviceName: web-server
    servicePort: 5000
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: web-server-backendconfig
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"
  timeoutSec: 600