apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scihive-backend
bases:
    - ../base

resources:
    - ingress.yaml
    - redis-volume.yaml

secretGenerator:
  - name: web-server-secrets
    envs:
      - .secrets
    type: Opaque

images:
  - name: web-server
    newName: gcr.io/scihive-prod/web-server

configMapGenerator:
  - name: web-server-config
    literals:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - FLASK_APP=src.app
      - PORT=5000
      - FRONTEND_URL=https://new.scihive.org
      - EXTERNAL_BASE_URL=https://arxiv.lyrn.ai
      - GOOGLE=1
      - REDIS_URL=redis://redis.scihive-backend.svc.cluster.local:6379
