apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: scihive-backend
spec:
  type: ExternalName
  # https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
  externalName: host.minikube.internal
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
