apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |
    appendonly yes
    protected-mode no
    bind 0.0.0.0
    port 6379
    dir /var/lib/redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
  namespace: scihive-backend
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0.8-alpine
          command:
            - redis-server
          args:
            - /etc/redis/redis.conf
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data-mount
              mountPath: /var/lib/redis
            - name: redis-conf
              mountPath: /etc/redis
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - if [ $(redis-cli ping) == "PONG" ]; then echo "ready!"; exit 0; else echo "not ready"; exit 1; fi;
            initialDelaySeconds: 5
            failureThreshold: 10
      volumes:
        - name: redis-conf
          configMap:
            name: redis-conf
            items:
              - key: redis.conf
                path: redis.conf
        - name: redis-data-mount
          persistentVolumeClaim:
            claimName: redis-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
  selector:
    app: redis
