apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server
  name: web-server
  namespace: scihive-backend
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 2
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: web-server
          resources: {} 
          readinessProbe:
            httpGet:
                path: /health
                port: main-port
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 5    
          ports:
            - name: main-port
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: web-server-config
            - secretRef:
                name: web-server-secrets
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
  name: web-server
  namespace: scihive-backend
  annotations:
    cloud.google.com/backend-config: '{"default": "web-server-backendconfig"}'
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: web-server
  type: NodePort